"""
constants.py

This module contains the constants, such as RESOLUTIONS, FPS, USER_NAME, GAME_NAME, BACKGROUND_IMAGE_PATH,
FONT_PATH, CHARACTER_WIDTH, CHARACTER_HEIGHT, NON_WALKABLE_AREAS and a class GameStateName. Which just stores the names
of game states. Used for convenience, because pycharm shows the full list of available names this way.
"""

import pygame

# Constants
RESOLUTIONS = [(800, 600), (1024, 768), (1280, 720), (1600, 900), (1920, 1080)]
FPS = 60

# Player name
USER_NAME = 'Player'

# Game meta
GAME_VERSION = '0.0.1'
GAME_NAME = 'Koshmaras'

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
DARK_GREEN = (0, 200, 0)
GRAY = (200, 200, 200)

# Image paths
BACKGROUND_PLACEHOLDER_IMAGE_PATH = 'resources/background/placeholder.jpg'
BACKGROUND_IMAGE_PATH = 'resources/background/'
first_list = [BACKGROUND_IMAGE_PATH + str(img) + '.jpg' for img in range(1, 42)]
second_list = [BACKGROUND_IMAGE_PATH + str(img) + '.jpg' for img in range(40, 1, -1)]
BACKGROUND_IMAGE_PATH_LIST = first_list + second_list
MAP_IMAGE_PATH = 'path/to/your/map_image.jpg'
BUTTON_FILE_PATH = 'resources/button/'
LOADING_IMAGE_PATH_LIST = ['resources/loading_screens/' + str(img) + '.png' for img in range(1, 3 + 1)]

# Fonts
FONT_PATH = 'resources/fonts/pixel-azure-bonds.ttf'
TEXT_FONT_PATH = 'resources/fonts/arial.ttf'

# Character variables
CHARACTER_SPEED = 5
CHARACTER_WIDTH = 25
CHARACTER_HEIGHT = 50

# Character sprites
sprite_path = 'resources/character_assets/char_template'
enemy_sprite_path = 'resources/character_assets/enemy_char_template'
SPRITE_PATH_LIST = [sprite_path + str(img) + '.png' for img in range(1, 4)]
ENEMY_SPRITE_PATH_LIST = [enemy_sprite_path + str(img) + '.png' for img in range(1, 4)]

# Main map
NON_WALKABLE_AREAS = [
    pygame.Rect(56, 295, 68, 600),  # building 1
    pygame.Rect(292, 274, 80, 600),  # building 2
    pygame.Rect(529, 263, 75, 600),  # building 3
    pygame.Rect(691, 145, 28, 100),  # building 4
    pygame.Rect(677, 2, 120, 63),  # building 5
    pygame.Rect(735, 299, 65, 88),  # building 6
    pygame.Rect(624, 80, 30, 70),  # building 7
]


# Game states
class GameStateName:
    INTRO_INPUT = 'INPUT'
    MENU = 'MENU'
    LOADING_SCREEN = 'LOADING_SCREEN'
    INTRO_SCENE_1 = 'INTRO_SCENE_1'
    INTRO_SCENE_2 = 'INTRO_SCENE_2'
    INTRO_SCENE_3 = 'INTRO_SCENE_3'
    INTRO_SCENE_4 = 'INTRO_SCENE_4'
    INTRO_SCENE_5 = 'INTRO_SCENE_5'
    INTRO_SCENE_6 = 'INTRO_SCENE_6'
    INTRO_SCENE_7 = 'INTRO_SCENE_7'
    BEDROOM_SCENE_1 = 'BEDROOM_SCENE_1'
    BEDROOM_SCENE_2 = 'BEDROOM_SCENE_2'
    BEDROOM_SCENE_3 = 'BEDROOM_SCENE_3'
    BEDROOM_SCENE_4 = 'BEDROOM_SCENE_4'
    BEDROOM_SCENE_5 = 'BEDROOM_SCENE_5'
    BEDROOM_SCENE_6 = 'BEDROOM_SCENE_6'
    BEDROOM_SCENE_7 = 'BEDROOM_SCENE_7'
    BEDROOM_SCENE_8 = 'BEDROOM_SCENE_8'
    BEDROOM_SCENE_9 = 'BEDROOM_SCENE_9'
    BEDROOM_SCENE_10 = 'BEDROOM_SCENE_10'
    BEDROOM_SCENE_11 = 'BEDROOM_SCENE_11'
    BEDROOM_SCENE_12 = 'BEDROOM_SCENE_12'
    BALCONY_SCENE_1 = 'BALCONY_SCENE_1'
    BALCONY_SCENE_2 = 'BALCONY_SCENE_2'
    BALCONY_SCENE_3 = 'BALCONY_SCENE_3'
    BALCONY_SCENE_4 = 'BALCONY_SCENE_4'
    BALCONY_SCENE_5 = 'BALCONY_SCENE_5'
    BALCONY_SCENE_6 = 'BALCONY_SCENE_6'
    BALCONY_SCENE_7 = 'BALCONY_SCENE_7'
    BALCONY_SCENE_8 = 'BALCONY_SCENE_8'
    BALCONY_SCENE_9 = 'BALCONY_SCENE_9'
    BALCONY_SCENE_10 = 'BALCONY_SCENE_10'
    BALCONY_SCENE_11 = 'BALCONY_SCENE_11'
    BALCONY_SCENE_12 = 'BALCONY_SCENE_12'
    BALCONY_SCENE_13 = 'BALCONY_SCENE_13'
    BALCONY_SCENE_14 = 'BALCONY_SCENE_14'
    BALCONY_SCENE_15 = 'BALCONY_SCENE_15'
    KITCHEN_SCENE_1 = 'KITCHEN_SCENE_1'
    KITCHEN_SCENE_2 = 'KITCHEN_SCENE_2'
    KITCHEN_SCENE_3 = 'KITCHEN_SCENE_3'
    KITCHEN_SCENE_4 = 'KITCHEN_SCENE_4'
    KITCHEN_SCENE_5 = 'KITCHEN_SCENE_5'
    KITCHEN_SCENE_6 = 'KITCHEN_SCENE_6'
    KITCHEN_SCENE_7 = 'KITCHEN_SCENE_7'
    KITCHEN_SCENE_8 = 'KITCHEN_SCENE_8'
    KITCHEN_SCENE_9 = 'KITCHEN_SCENE_9'
    KITCHEN_SCENE_10 = 'KITCHEN_SCENE_10'
    KITCHEN_SCENE_11 = 'KITCHEN_SCENE_11'
    KITCHEN_SCENE_12 = 'KITCHEN_SCENE_12'
    BATHROOM_SCENE_1 = 'BATHROOM_SCENE_1'
    BATHROOM_SCENE_2 = 'BATHROOM_SCENE_2'
    BATHROOM_SCENE_3 = 'BATHROOM_SCENE_3'
    BATHROOM_SCENE_4 = 'BATHROOM_SCENE_4'
    LAIPTINE_SCENE_1 = 'LAIPTINE_SCENE_1'
    LAIPTINE_SCENE_2 = 'LAIPTINE_SCENE_2'
    LAIPTINE_SCENE_3 = 'LAIPTINE_SCENE_3'
    LAIPTINE_SCENE_4 = 'LAIPTINE_SCENE_4'
    LAIPTINE_SCENE_5 = 'LAIPTINE_SCENE_5'
    LAIPTINE_SCENE_6 = 'LAIPTINE_SCENE_6'
    NARVELIS_SCENE_1 = 'NARVELIS_SCENE_1'
    NARVELIS_SCENE_2 = 'NARVELIS_SCENE_2'
    NARVELIS_SCENE_3 = 'NARVELIS_SCENE_3'
    NARVELIS_SCENE_4 = 'NARVELIS_SCENE_4'
    NARVELIS_SCENE_5 = 'NARVELIS_SCENE_5'
    NARVELIS_SCENE_6 = 'NARVELIS_SCENE_6'
    NARVELIS_SCENE_7 = 'NARVELIS_SCENE_7'
    NARVELIS_SCENE_8 = 'NARVELIS_SCENE_8'
    NARVELIS_SCENE_9 = 'NARVELIS_SCENE_9'
    NARVELIS_SCENE_10 = 'NARVELIS_SCENE_10'
    NARVELIS_SCENE_11 = 'NARVELIS_SCENE_11'
    NARVELIS_SCENE_12 = 'NARVELIS_SCENE_12'
    NARVELIS_SCENE_13 = 'NARVELIS_SCENE_13'
    NARVELIS_SCENE_14 = 'NARVELIS_SCENE_14'
    NARVELIS_SCENE_15 = 'NARVELIS_SCENE_15'
    NARVELIS_SCENE_16 = 'NARVELIS_SCENE_16'
    NARVELIS_SCENE_17 = 'NARVELIS_SCENE_17'
    NARVELIS_SCENE_18 = 'NARVELIS_SCENE_18'
    NARVELIS_SCENE_19 = 'NARVELIS_SCENE_19'
    NARVELIS_SCENE_20 = 'NARVELIS_SCENE_20'
    NARVELIS_SCENE_21 = 'NARVELIS_SCENE_21'
    NARVELIS_SCENE_22 = 'NARVELIS_SCENE_22'
    NARVELIS_SCENE_23 = 'NARVELIS_SCENE_23'
    STORE_SCENE_1 = 'STORE_SCENE_1'
    STORE_SCENE_2 = 'STORE_SCENE_2'
    STORE_SCENE_3 = 'STORE_SCENE_3'
    STORE_SCENE_4 = 'STORE_SCENE_4'
    STORE_SCENE_5 = 'STORE_SCENE_5'
    STORE_SCENE_6 = 'STORE_SCENE_6'
    STORE_SCENE_7 = 'STORE_SCENE_7'
    STORE_SCENE_8 = 'STORE_SCENE_8'
    STORE_SCENE_9 = 'STORE_SCENE_9'
    STORE_SCENE_10 = 'STORE_SCENE_10'
    STORE_SCENE_11 = 'STORE_SCENE_11'
    STORE_SCENE_12 = 'STORE_SCENE_12'
    STORE_SCENE_13 = 'STORE_SCENE_13'
    STORE_SCENE_14 = 'STORE_SCENE_14'
    STORE_SCENE_15 = 'STORE_SCENE_15'
    STORE_SCENE_16 = 'STORE_SCENE_16'
    STORE_SCENE_17 = 'STORE_SCENE_17'
    STORE_SCENE_18 = 'STORE_SCENE_18'
    STORE_SCENE_19 = 'STORE_SCENE_19'
    STORE_SCENE_20 = 'STORE_SCENE_20'
    STORE_SCENE_21 = 'STORE_SCENE_21'
    STORE_SCENE_22 = 'STORE_SCENE_22'
    STORE_SCENE_23 = 'STORE_SCENE_23'
    STORE_SCENE_24 = 'STORE_SCENE_24'
    STORE_SCENE_25 = 'STORE_SCENE_25'
    STORE_SCENE_26 = 'STORE_SCENE_26'
    STORE_SCENE_27 = 'STORE_SCENE_27'
    STORE_SCENE_28 = 'STORE_SCENE_28'
    STORE_SCENE_29 = 'STORE_SCENE_29'
    SLEEP_SCENE_1 = 'SLEEP_SCENE_1'
    SLEEP_SCENE_2 = 'SLEEP_SCENE_2'
    GAME_OVER = 'GAME_OVER'
    GAME_COMPLETED = 'GAME_COMPLETED'
    WORLD_MOVEMENT = 'WORLD_MOVEMENT'
    NIGHTMARE_WORLD_MOVEMENT = 'NIGHTMARE_WORLD_MOVEMENT'
